#pragma once

#include "Rainbow_Wave.h"
#include "Rainbow_Wave_With_Glitter.h"
#include "Glitter.h"
#include "Sinelon.h"
#include "Mr_Poopy_Worm.h"
#include "Solid_Color.h"
#include "Meteor.h"
#include "Multi_Meteor.h"
#include "Wave.h"
#include "Crazy_Time.h"
#include "Confetti.h"
#include "Color_Waves.h"
#include "Boom.h"
#include "Boom_2.h"
#include "Rapid_Boom.h"
#include "Drip_Splosion.h"
#include "Strobe.h"
#include "Circle_Strobe.h"
#include "Boomer.h"
#include "Splosion.h"
#include "Dripper.h"
#include "Solid_Color_Palette.h"

#include "Artnet.h"